/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -V -c QlipmonAdaptor -i database_entry.h -a qlipmon_adaptor.h: ../qlipmon.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef QLIPMON_ADAPTOR_H
#define QLIPMON_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "database_entry.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface QLIPMON_DBUS_FQDN
 */
class QlipmonAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", QLIPMON_DBUS_FQDN)
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"" QLIPMON_DBUS_FQDN "\">\n"
"    <property access=\"readwrite\" type=\"b\" name=\"broadcast\"/>\n"
"    <signal name=\"updated\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"text\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"mode\"/>\n"
"    </signal>\n"
"    <method name=\"setText\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"text\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"mode\"/>\n"
"    </method>\n"
"    <method name=\"setText\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"text\"/>\n"
"    </method>\n"
"    <method name=\"getLastText\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"mode\"/>\n"
"    </method>\n"
"    <method name=\"getLastText\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"getTextHistory\">\n"
"      <arg direction=\"out\" type=\"as\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"mode\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"duplicates\"/>\n"
"    </method>\n"
"    <method name=\"getTextHistory\">\n"
"      <arg direction=\"out\" type=\"as\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"mode\"/>\n"
"    </method>\n"
"    <method name=\"getTextHistory\">\n"
"      <arg direction=\"out\" type=\"as\"/>\n"
"    </method>\n"
"    <method name=\"getHistory\">\n"
"      <arg direction=\"out\" type=\"a(tsix)\"/>\n"
"      <annotation value=\"QList&lt;database_entry&gt;\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    QlipmonAdaptor(QObject *parent);
    virtual ~QlipmonAdaptor();

public: // PROPERTIES
    Q_PROPERTY(bool broadcast READ broadcast WRITE setBroadcast)
    bool broadcast() const;
    void setBroadcast(bool value);

public Q_SLOTS: // METHODS
    QList<database_entry> getHistory();
    QString getLastText();
    QString getLastText(int mode);
    QStringList getTextHistory();
    QStringList getTextHistory(int mode);
    QStringList getTextHistory(int mode, bool duplicates);
    void setText(const QString &text);
    void setText(const QString &text, int mode);
Q_SIGNALS: // SIGNALS
    void updated(const QString &text, int mode);
};

#endif
